### ISSUE TITLE
Ability to run `postinstall.js` or some sort of aliasing

### ISSUE THREAD

**Issue by surdaft** [davidsiems/bitpacker#4]
The ability to add a postinstall.js file that adds an alias for our packages would be great. As well as maybe an auto alias, or package.txt option?

> ooo yah, some kind of postinstall.js support so pkgs can print welcome messages, do aliasing, etc.
> smolgumball

**Comment by davidsiems** [comment]
Added an "aliases" and "welcome" field to package.txt.
