### ISSUE TITLE
CORS errors when attempting to install packages from browser version of the game

### ISSUE THREAD

**Issue by smolgumball** [davidsiems/bitpacker#5]
![image](https://user-images.githubusercontent.com/53015256/149463229-72c26757-bae2-4eaf-8b7a-cdeccee9c92b.png)

`bitpacker` fully up to date, not sure what gives! Browse command works fine, but `bp add [package-name]` fails as above.

**Comment by davidsiems** [comment]
Were you running this from the website? I've only been testing via the steam client, could explain it....

**Comment by smolgumball** [comment]
Aye, was running from website @ https://danielyxie.github.io/bitburner. Also worth noting that this version can sometimes drift a bit out of date, so... yay more variables :) 

But good news is `bp add` seems to be working great. Thanks @davidsiems!
