### ISSUE TITLE
`bp update-bp` prints that a new version is available even though it's being updated

### ISSUE THREAD

**Issue by Sleaker** [davidsiems/bitpacker#7]
running bp update-bp should supress the notification that there is an update for bp available, otherwise it can be a little confusing for the user if bp updated, but still needs another update.

also: README.md doesn't have the bp update-bp in the getting started command list to let the user know that they can update the script via this method, or that the script will auto-notify users when it needs an update.

Also: the installation command isn't wrapped in code tags.

**Comment by davidsiems** [comment]
Fixed! Thanks for taking the time to let me know.
